### ISSUE TITLE
error when try to fetch store data 

### ISSUE THREAD

**Issue by moayyaed** [rahulsahay19/eCommerce-App#2]
Internal Server Error - Refresing the page will make exception disappear
Error: It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 6s ago, v: 2.1.30.38891
Note:- Check server error logs

https://localhost:5001/api/products?sort=priceAsc&pageIndex=1&pageIndex=10

{"statusCode":500,"message":"It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 117s ago, v: 2.1.30.38891"}

**Comment by rahulsahay19** [comment]
Your redis server isn't started. You need to start that first, in order to fetch the app. Thanks.
