### ISSUE TITLE
basket and sign up and login not working where click on it

### ISSUE THREAD

**Issue by moayyaed** [rahulsahay19/eCommerce-App#3]
Request URL: https://localhost:4200/basket-basket-module.js
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Referer: https://localhost:4200/shop
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

*****
2882: URL_REQUEST
https://localhost:4200/basket-basket-module.js
Start Time: 2020-06-17 08:22:43.634

t=71712 [st=  0] +REQUEST_ALIVE  [dt=305]
                  --> priority = "LOWEST"
                  --> traffic_annotation = 101845102
                  --> url = "https://localhost:4200/basket-basket-module.js"
t=71712 [st=  0]    NETWORK_DELEGATE_BEFORE_URL_REQUEST  [dt=0]
t=71712 [st=  0]   +URL_REQUEST_START_JOB  [dt=305]
                    --> initiator = "https://localhost:4200"
                    --> load_flags = 65536 (SUPPORT_ASYNC_REVALIDATION)
                    --> method = "GET"
                    --> network_isolation_key = "https://localhost:4200 https://localhost:4200"
                    --> privacy_mode = 0
                    --> site_for_cookies = "SiteForCookies: {scheme=https; registrable_domain=localhost}"
                    --> url = "https://localhost:4200/basket-basket-module.js"
t=71712 [st=  0]      COOKIE_INCLUSION_STATUS
                      --> operation = "send"
                      --> status = "INCLUDE, DO_NOT_WARN"
t=71712 [st=  0]      COOKIE_INCLUSION_STATUS
                      --> operation = "send"
                      --> status = "INCLUDE, DO_NOT_WARN"
t=71712 [st=  0]      COOKIE_INCLUSION_STATUS
                      --> operation = "send"
                      --> status = "INCLUDE, DO_NOT_WARN"
t=71712 [st=  0]      COOKIE_INCLUSION_STATUS
                      --> operation = "send"
                      --> status = "INCLUDE, DO_NOT_WARN"
t=71712 [st=  0]      COOKIE_INCLUSION_STATUS
                      --> operation = "send"
                      --> status = "INCLUDE, DO_NOT_WARN"
t=71712 [st=  0]      COOKIE_INCLUSION_STATUS
                      --> operation = "send"
                      --> status = "INCLUDE, DO_NOT_WARN"
t=71712 [st=  0]      NETWORK_DELEGATE_BEFORE_START_TRANSACTION  [dt=0]
t=71712 [st=  0]      HTTP_CACHE_GET_BACKEND  [dt=0]
t=71712 [st=  0]      HTTP_CACHE_OPEN_OR_CREATE_ENTRY  [dt=0]
t=71712 [st=  0]      HTTP_CACHE_ADD_TO_ENTRY  [dt=0]
t=71713 [st=  1]     +HTTP_STREAM_REQUEST  [dt=303]
t=71713 [st=  1]        HTTP_STREAM_JOB_CONTROLLER_BOUND
                        --> source_dependency = 2884 (HTTP_STREAM_JOB_CONTROLLER)
t=72016 [st=304]        HTTP_STREAM_REQUEST_BOUND_TO_JOB
                        --> source_dependency = 2885 (HTTP_STREAM_JOB)
t=72016 [st=304]     -HTTP_STREAM_REQUEST
t=72017 [st=305]      URL_REQUEST_DELEGATE_SSL_CERTIFICATE_ERROR  [dt=0]
t=72017 [st=305]      CANCELLED
                      --> net_error = -202 (ERR_CERT_AUTHORITY_INVALID)
t=72017 [st=305]   -URL_REQUEST_START_JOB
                    --> net_error = -202 (ERR_CERT_AUTHORITY_INVALID)
t=72017 [st=305]    URL_REQUEST_DELEGATE_RESPONSE_STARTED  [dt=0]
t=72017 [st=305] -REQUEST_ALIVE

**Comment by rahulsahay19** [comment]
Have you installed the certificate? It expects to have https://localhost:4200/ . so, you can have self sign cert to create and run against that or you can enable ssl in angular via angular.json and then place self signed cert in source code where angular is in some folder and specify the path in angular.json. That way, your issue will be resolved. Thanks.
